### ISSUE TITLE
No album art shown with System theme selected

### ISSUE THREAD

**Issue by vk2him** [music-assistant/music-assistant-desktop#3]
I've tried Windows and Mac versions - Album art isn't displayed when System theme is selected. Also occurs with latest version 0.0.0.14

**Comment by Un10ck3d** [comment]
Hey, thanks a lot for reporting the issue! 🙂 Yeah I think there are a few issues with the system theme in general. I will look at it when I get home tomorrow 👍

**Comment by vk2him** [comment]
Thanks, yes it seems to be fine now
